cache: fix the cacheline not aligned issue
The module who wants to read LBA had better deliver
the dram buffer which is L1 cacheline aligned(64 byte).

The error log like below:
	......
	ERROR: v7_dcache_inval_range - start address is not aligned - 0x059bbecc
	ERROR: v7_dcache_inval_range - stop address is not aligned - 0x059bc0cc
	......

Change-Id: If21d483fa9508de1dbc9dbc9deda6eb325d81eda
Signed-off-by: Joseph Chen <chenjh@rock-chips.com>