Kconfig: Select SPL_HASH_SUPPORT if ARMV8_CRYPTO
The commit (82a88d02ff6 lib: rsa-checksum: Add ARMv8 CE support) makes
CONFIG_SPL_HASH_SUPPORT=y to be required when CONFIG_SPL_ARMV8_CRYPTO=y.

Fix the compile fail:
  lib/built-in.o: In function `rsa_hash_calculate':
  lib/rsa/rsa-checksum.c:30: undefined reference to `hash_progressive_lookup_algo'
  Segmentation fault (core dumped)
  scripts/Makefile.spl:375: recipe for target 'spl/u-boot-spl' failed

Signed-off-by: Joseph Chen <chenjh@rock-chips.com>
Change-Id: If2afb17ee12c306562181d0f6e132fbe118cef06