include: rockusb: Fix compile problem without CONFIG_CMD_ROCKUSB
If you use toolchain: gcc-arm-10.3-2021.07-x86_64-aarch64-none-linux-gnu

Maybe you will encounter compile problem like this:
include/rockusb.h:78:38: error：array ‘rkusb_fs_function' assumed to have one element [-Werror]
   78 | static struct usb_descriptor_header *rkusb_fs_function[];
      |                                      ^~~~~~~~~~~~~~~~~
include/rockusb.h:79:38: error：array ‘rkusb_hs_function' assumed to have one element [-Werror]
   79 | static struct usb_descriptor_header *rkusb_hs_function[];
      |                                      ^~~~~~~~~~~~~~~~~

Change-Id: I686e56e6b86c9abf8f267b315fb82be6406e5bda
Signed-off-by: Xuhui Lin <xuhui.lin@rock-chips.com>