boot: Kconfig: default select AES for ANDROID_WRITE_KEYBOX
youtube_keybox.c, built under CONFIG_ANDROID_WRITE_KEYBOX, calls
aes_expand_key() and aes_cbc_decrypt_blocks() from lib/aes.c, which
is only compiled when CONFIG_AES is set.

Enabling CONFIG_USB_FUNCTION_ROCKUSB exposes the latent bug:
f_rockusb.c calls write_keybox_to_secure_storage() under
"#ifdef CONFIG_ANDROID_WRITE_KEYBOX", which activates the chain and
forces the linker to resolve the AES symbols. Without CONFIG_AES the
link fails with:

  boot/android/youtube_keybox.c:54: undefined reference to `aes_expand_key'
  boot/android/youtube_keybox.c:56: undefined reference to `aes_cbc_decrypt_blocks'

Change-Id: I34eeabdf753e4eaa8314c8e10405d0a299dc7a95
Signed-off-by: Frank Wang <frank.wang@rock-chips.com>