video/drm: vop2: Fix compile errors in rk3576_extra_alpha()
If the compilation toolchain is set to aarch64-rockchip1240-linux-gnu,
there will be compile errors:

In function 'rk3576_extra_alpha',
  inlined from 'rk3576_setup_alpha' at drivers/video/drm/rockchip_vop2.c:7198:3:
drivers/video/drm/rockchip_vop2.c:6950:33: error: 'extra_win_zpos' may be used uninitialized [-Werror=maybe-uninitialized]
 6950 |         printf("Only esmart1/3 can overlay from vp1: %s[%d],extra win:%s[%d]\n",
      |                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 6951 |                 win_data->name, vop2_zpos->zpos,
      |                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 6952 |                 extra_win_data->name, extra_win_zpos);
      |                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
drivers/video/drm/rockchip_vop2.c: In function 'rk3576_setup_alpha':
drivers/video/drm/rockchip_vop2.c:6929:12: note: 'extra_win_zpos' was
declared here
 6929 |         u8 extra_win_zpos;
      |              ^~~~~~~~~~~~~

Change-Id: Ib6e119f84c3decaf92f8bc182743ac3437e0199c
Signed-off-by: Damon Ding <damon.ding@rock-chips.com>