common: edid: Sync EDID helper interfaces with kernel
This patch aligns U-Boot EDID implementation with kernel DRM for
easier maintenance and future upgrades, and brings two key
improvements:

1. Fix EDID checksum recalculation when discarding invalid blocks

When cleaning up invalid EDID blocks, recalculate and update both
extensions field and main block checksum. Otherwise drm_add_edid_modes
fails EDID validation and cannot read display modes.

Take BOE NE160QDM-NY1 eDP panel as example, its raw main block contains
unstable padding bytes at the end:

[00] GOOD 00 ff ff ff ff ff ff 00 09 e5 85 09 00 00 00 00
[00] GOOD 1c 1e 01 04 b5 22 15 78 03 7c e5 a4 55 4c 9f 26
[00] GOOD 0f 50 54 00 00 00 01 01 01 01 01 01 01 01 01 01
[00] GOOD 01 01 01 01 01 01 6b 6e 00 a0 a0 40 84 60 30 20
[00] GOOD 36 00 58 d7 10 00 00 1a 00 00 00 fd 0c 3c a5 1f
[00] GOOD 1f 4e 01 0a 20 20 20 20 20 20 00 00 00 fe 00 42
[00] GOOD 4f 45 20 43 51 0a 20 20 20 20 20 20 00 00 00 fe
[00] GOOD 00 4e 45 31 36 30 51 44 4d 2d 4e 59 31 0a 02 ec

Due to the invalid extension block 2, the actual main blcok should be:

[00] GOOD 00 ff ff ff ff ff ff 00 09 e5 85 09 00 00 00 00
[00] GOOD 1c 1e 01 04 b5 22 15 78 03 7c e5 a4 55 4c 9f 26
[00] GOOD 0f 50 54 00 00 00 01 01 01 01 01 01 01 01 01 01
[00] GOOD 01 01 01 01 01 01 6b 6e 00 a0 a0 40 84 60 30 20
[00] GOOD 36 00 58 d7 10 00 00 1a 00 00 00 fd 0c 3c a5 1f
[00] GOOD 1f 4e 01 0a 20 20 20 20 20 20 00 00 00 fe 00 42
[00] GOOD 4f 45 20 43 51 0a 20 20 20 20 20 20 00 00 00 fe
[00] GOOD 00 4e 45 31 36 30 51 44 4d 2d 4e 59 31 0a 01 ed

The fix ensures checksum matches after trimming noise bytes.

2. Introduce drm_edid helper APIs in preparation for eDP panel driver

These new interfaces will be used to fetch EDID information via AUX bus
from eDP panel later.

In addition, remove duplicate EDID_LENGTH macro in edp_rk3288.h. The
local EDID_LENGTH definition conflicts with the standard one in edid.h,
triggering redefinition compile error when warnings are treated as
errors. Remove the redundant local macro to resolve the build failure:

17:39:14 In file included from drivers/video/rockchip/rk_vop.c:20:0:
17:39:14 ./arch/arm/include/asm/arch/edp_rk3288.h:529:0: error:
   "EDID_LENGTH" redefined [-Werror]
17:39:14  #define EDID_LENGTH    0x80
17:39:14
17:39:14 In file included from drivers/video/rockchip/rk_vop.c:12:0:
17:39:14 include/edid.h:22:0: note: this is the location of the previous
   definition
17:39:14  #define EDID_LENGTH 128
17:39:14
17:39:14 cc1: all warnings being treated as errors

Change-Id: Iee53ff98e45ef8f2f633f46d54a0df21f5bdf7e5
Signed-off-by: Damon Ding <damon.ding@rock-chips.com>