video/drm: vop2: Initialize &vop2_alpha_config in rk3576_extra_alpha()
If the compilation toolchain is updated to
gcc-arm-10.3-2021.07-x86_64-aarch64-none-linux-gnu, there will be a
compile error:

drivers/video/drm/rockchip_vop2.c: In function ‘rk3576_setup_alpha’:
drivers/video/drm/rockchip_vop2.c:6924:27: error: ‘alpha_config’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
 6924 |  struct vop2_alpha_config alpha_config;

Fixes: 3c6b8d00e94 ("video/drm: vop2: Sync the default extra layer alpha configs with Kernel for rk3576")
Change-Id: Ie02627c419b12ffbc990143c50ce6b28a010c772
Signed-off-by: Damon Ding <damon.ding@rock-chips.com>